### ISSUE TITLE
Using mediastream-to-webm for client without node js

### ISSUE THREAD

**Issue by Rgckyd** [t-mullen/mediastream-to-webm#1]
Hi ! I'm curently trying to use your mediastream-to-webm.js library to send a video stream by socket from client to server. However you seemed to use node js require to include mediastream-to-webm in your client and we'd need to build our client without node js. So is it possible to only include it with a script tag without having undefined mtw var ?
In that case could you give me some advices to call the mtw variable ?
The purpose of our project is to use a webcam in client side and to send it by socket to a raspberry server in order to display it. You'll find attached our client source code.
Thank you !
[Index2.zip](https://github.com/t-mullen/mediastream-to-webm/files/2581578/Index2.zip)

**Comment by t-mullen** [comment]
This library uses Browserify to build “Node.js”-style (CommonJS) modules into something the browser can use. 

You don’t need to use Browserify to import the module though, any bundler that supports CommonJS should work (WebPack, Rollup, etc).

If you’re using vanilla ES6 imports without any bundler, you should be able to just import the bundled file in /dist.

**Comment by t-mullen** [comment]
If none of the above applies, including the bundled file in /dist in a script tag will define a global variable you can use.
