### ISSUE TITLE
if we can only send the chunk but aren't allowed to connect to the enc stream

### ISSUE THREAD

**Issue by ChrisChiasson** [t-mullen/mediastream-to-webm#2]
Summary for future visitors: to use the chunks provided in the `EncodedStream.on('data')` event, @t-mullen gave the answer below. The chunk can't be provided to Media Source Extensions, instead it must be provided to the `DecodedStream`. If you are using `DecodedStream.write` to do that, you must write the chunk in the same format you received it from `EncodedStream`, which is a `Uint8Array`. Thanks @t-mullen!

**Comment by t-mullen** [comment]
Do you mean why can't you send the webm chunks directly instead of using this module to encode them? You could; all this module does is make it easier to do that, as well as allowing people to jump in mid-stream by packing the header alongside every chunk. You could feed directly into MSE, as long as you feed the header first and don't split chunks.

Normal webm chunk stream:
```
[header][chunk][chunk]...
```

This module:
```
[header][chunk][header][chunk][header][chunk]...
```

**Comment by ChrisChiasson** [comment]
Over lunch I tried with the following code (slightly cleaned up). The receiving plain MSE returns an error `"CHUNK_DEMUXER_ERROR_APPEND_FAILED: Append: stream parsing failed. Data size=253 append_window_start=0 append_window_end=inf"`. I will try to produce a single-page minimal example tonight.
````
const mediaType = 'video/webm; codecs="opus,vp8"';
let m = mtw.EncodedStream(s,{interval: 100,mimeType: mediaType});
m.on('data',d=>{sendChunk(new File([new Blob([d])],socket.id));});
````
P.S. The inner new Blob is for converting from Uint8Array (this is what the console log said the data was). I'm not sure if I"m doing that part right, or any of it, really.

**Comment by t-mullen** [comment]
You're still encoding in that example, MSE won't be able to parse that. If you encode, you'll need to decode before parsing.

MSE is really picky even under normal conditions, this module uses [MediaSource](https://www.npmjs.com/package/mediasource) since it handles a lot of the weird behaviour.

I don't think I'm understanding what it is you want to do.

**Comment by ChrisChiasson** [comment]
After your comment, I tried to implement the decoder in my node/browserify app, but ran into another problem. So, I spent this evening trying to isolate everything into one static html file, but I ran out of time before I have to go to bed. The static file has problems because I am too ignorant of JS to know how to expose DecodedStream into my script. The console is telling me it's undefined, though it does find and load the library file. In the real web app, the failure occurrs on the d.write(b) call in appendBlob. The console says `Uncaught TypeError: Invalid non-string/buffer chunk at validChunk (_stream_writable.js:304) at DecodedStream.Writable.write (_stream_writable.js:332) at FileReader.r.addEventListener.e (client.js:113)`. Hopefully this should better expose my intent, and once again, thank you for your valuable time.
````
<!DOCTYPE html>
<html>
 <head>
  <title>mediastream-to-webm</title>
 </head>
 <body>
  <article>
   <button id="start">Start</button>
   <video id="out-video"></video>
   <video id="in-video" width="320" height="240" controls></video>
  </article>
  <script src="mediastream-to-webm.js"></script>
  <script>

let inVideo = document.getElementById('in-video'); // decoder
let outVideo = document.getElementById('out-video'); // encoder
let startButton = document.getElementById('start');
const mediaType = 'video/webm; codecs="opus,vp8"';

function appendBlob(b,d){
 let r = new FileReader();
 r.addEventListener("load",e=>{
  d.write(r.result);},{once:true});
 r.readAsArrayBuffer(b);
}

let dec = DecodedStream({videoElement: inVideo, mimeType: mediaType});

function gotChunk(f){
 appendBlob(f,dec);
}

function onStream(s){
 outVideo.muted = true;
 outVideo.srcObject = s;
 outVideo.play();
 let enc = EncodedStream(s,{interval: 1000,mimeType: mediaType});
 enc.on('data',d=>{gotChunk(new File([new Blob([d])],"id"));});
}

inVideo.onerror=()=>{console.log("inVideo error ",inVideo.error);};
inVideo.oncanplay=()=>{inVideo.play();};

startButton.onclick=()=>{
 navigator.mediaDevices.getUserMedia({audio:true,video:true}).then(onStream);
};

  </script>
 </body>
</html>

````

**Comment by t-mullen** [comment]
You don't have to directly pipe stream objects into each other, it's just an abstraction of the chunk sequence. If you aren't sending the data through a stream, just use the 'data' event and `.write(chunk)`.

```javascript
var encodedStream = mtw.EncodedStream(mediaStream)
encodeStream.on('data', (chunk) => {
   send(chunk)
})
```
```javascript
var decodedStream = mtw.DecodedStream()
function onChunkFromSomewhere (chunk) {
  decodedStream.write(chunk)
}
```

This is equivalent to:
```javascript
encodedStream.pipe(decodedStream)
```

**Comment by t-mullen** [comment]
Nevermind, you're already using that.

My guess is you aren't converting the data back into the original chunk format. Try logging what is coming out of the `data` event and what you are writing into the decoder stream and comparing.

**Comment by t-mullen** [comment]
Try converting the ArrayBuffer into a Uint8Array before writing:

```javascript
d.write(new Uint8Array(r.result));
```

**Comment by ChrisChiasson** [comment]
I tried the fix you mentioned on my web app. The errors disappeared from the console, but the receiving tab's player loaded with a white background, and when I hit play, nothing happens. After a while, the receiving tab crashes with an out of memory error. I'll try to get the single page version working to see if I isolate the problem better. Thanks very much for your help!

**Comment by ChrisChiasson** [comment]
... and happy Thanksgiving tomorrow!
